### ISSUE TITLE
Помощь в разработке

### ISSUE THREAD

**Issue by prospero78** [AntKrotov/oberon-07-compiler#1]
Антон, приветствую уважаемый!)
Чем могу помочь?)
Лицензия BSD-2 радует безмерно))

**Comment by AntKrotov** [comment]
Привет. Что можно сделать:

- поддержка Linux. Я могу сделать так, чтобы компилятор выдавал двоичный файл в специальном формате с кодом, данными, релоками, импортом, экспортом. В общем, всем необходимым для компоновки исполняемого файла. Так, чтобы компоновщик первое время вообще мог быть отдельной программой. Тут есть проблема: без libc в Linux никак. Поэтому, вероятно потребуется еще и gcc для окончательной линковки.
- библиотеки, примеры, обертка для SDL и т.п.
- третий бэк-энд. Промежуточное представление (стэк-машина) очень примитивное и не подходит для хорошей кодогенерации. Но транслируется довольно просто. Хоть как-то, но будет работать. В процессе разработки третьего бэк-энда можно будет еще и внести улучшения в промежуточный код.
- тестирование, баг-репорты

Можешь еще что-то добавить от себя.

**Comment by prospero78** [comment]
Хорошо, хоть и сильно занят попробую что-нибудь сделать. А ты уж сам посмотри.
