### ISSUE TITLE
Кастинг по типу или я туплю?

### ISSUE THREAD

**Issue by prospero78** [AntKrotov/oberon-07-compiler#11]
1) Сделал базовый тип
2) Сделал производный тип от базового
3) Сделал тип указатель на производный тип
4) В процедуру требую указатель на базовый тип, передаю указатель на производный тип.
5) Компилятор сходит с ума. assertion failure, module PROG, line 486.
Если это правильное поведение, тогда кастинг по производным типам из базового в компиляторе невозможен?
Сделал передачу напрямую производного типа -- результат тот же.

**Comment by AntKrotov** [comment]
Если assert, то это ошибка в компиляторе. Но мне не удалось ее воспроизвести по описанию. Тут нужен пример кода, если можно.

**Comment by prospero78** [comment]
Хорошо, вечером архив с кодом перекину.

**Comment by AntKrotov** [comment]
akron1_m@mail.ru

**Comment by AntKrotov** [comment]
Я только что наткнулся на эту ошибку (assertion failure, module PROG, line 486). Правда, она воспроизводилась совсем по-другому. Тем не менее, думаю, что я ее исправил (коммит 386 модуль PROG).

**Comment by prospero78** [comment]
> Я только что наткнулся на эту ошибку (assertion failure, module PROG, line 486). Правда, она воспроизводилась совсем по-другому. Тем не менее, думаю, что я ее исправил (коммит 386 модуль PROG).

Ну вот! Я же говорил!))
