### ISSUE TITLE
Спасибо за Oberon07

### ISSUE THREAD

**Issue by leency** [AntKrotov/oberon-07-compiler#13]
Хочу сказать огромное спасибо за отличный компилятор, поддержку KolibriOS и удобную читалку FB2Reader!

Я обновил Oberon07 на svn://kolibrios.org и добавил ссылку на данный репозитарий.
Если будет время, было бы клево увидеть авто-определение кодировки в FB2Reader, и совсем уж хорошо - поиск. 

С уважением,
Кирилл

**Comment by AntKrotov** [comment]
> Хочу сказать огромное спасибо за отличный компилятор, поддержку KolibriOS и удобную читалку FB2Reader!

Компилятор игрушечный (промышленный, я конечно не собирался делать), но кое-какие преимущества над другими подобными проектами всё же имеет. Хотя я, как обычно, не вполне доволен тем, что сделал. Всегда кажется, что мог бы сделать лучше...

> Я обновил Oberon07 на svn://kolibrios.org и добавил ссылку на данный репозитарий.

Это хорошо, а то я утратил доступ к SVN и не знаю, буду ли его восстанавливать, так как мое участие в проекте KolibriOS практически прекратилось. Как раз вот недавно подумал, что надо бы тебя попросить обновить компилятор, чтобы после меня всё осталось в сколько-нибудь завершенном виде.

> Если будет время, было бы клево увидеть авто-определение кодировки в FB2Reader, и совсем уж хорошо - поиск.

Я уже давно не пишу для KolibriOS, но от поддержки своего кода я пока не отказываюсь. Может быть посмотрю, что там можно сделать.

**Comment by leency** [comment]
К видео о КолибриОС был оставлен комментарий:

> С чем связаны приколы с кодировками? Даже во времена спектрума лет 20 назад работало автоопределение. Иногда оно срабатывало неверно, и для этого есть ручной выбор. А тут мне надо знать,  в какой кодировке файл (да хз, только что скачал!) и исходя из этого выбирать одно из 3-х или больше приложений.

Так что я в WebView и Quark уже добавил авто-определение кодировки.
Ранее был еще TxtRead, но он канул в лету, т.к. FB2View отображает KF-шрифты значительно лучше и если это книга, то ее лучше читать в FB2View. 

Ну и поиск тоже полезная штука, потому как есть идеи перевести некоторую документацию в FB2 формат.
