### ISSUE TITLE
Ошибка компиляции под Linux

### ISSUE THREAD

**Issue by prospero78** [AntKrotov/oberon-07-compiler#16]
```bash
walera@walera-lin:~/coding/gowork/src/github.com/prospero78/obGraph$ SelfLinux64.sh
Compiler
index out of range
module: HOST
line: 83
/home/walera/bin/SelfLinux64.sh: строка 2: @pause: команда не найдена
```

**Comment by prospero78** [comment]
Проблема решена:
1) локальным копированием всего компилятора себе в проект
2) Указанием путей относительно файла КОМПИЛЯТОРА.

**Comment by AntKrotov** [comment]
Да, есть такая недоработка: относительный путь к главному модулю проекта задаётся относительно файла компилятора. Размещение папки lib также фиксировано относительно файла компилятора. Чтобы устранить этот недостаток, мне нужно чёткое описание того, как это должно работать "по-нормальному" с примерами.

**Comment by prospero78** [comment]
Прям вот лог при компиляции:
```bash
walera@walera-lin:~/coding/gowork/src/github.com/prospero78/obGraph$ make run.app
Compiler "../src/Main.ob07" linux64exe -out "../bin/main"
Compiler
index out of range
module: HOST
line: 83
./bin/main
X connection to :0 broken (explicit kill or server shutdown).
make: *** [Makefile:3: run.app] Ошибка 1
```

**Comment by AntKrotov** [comment]
Ну да, есть проблема с относительными путями (я всегда полный использую). Позже посмотрю.
По пакетам, это типа как подсистемы в блэкбоксе? При импорте модуля надо будет кроме имени указать еще и пакет/подсистему. Как это лучше сделать?

**Comment by prospero78** [comment]
Чтобы не ломать совместимость с сообщением о языке -- предлагаю не делать, как подсистемы в БлекБоксе (всё-таки, когда много каталогов -- там начинается адъ), а сделать в комментариях опции компилятора. Что-то вроде такого:
```pascal
(* $IMP:square=./graph/square.ob07 *)
IMPORT square;
```

**Comment by AntKrotov** [comment]
Лучше, наверно, сделать нормально, а не "совместимо". В общем-то, уже только символ "_" в идентификаторах не совместим с сообщением о языке. Так что...
А если вот так?
`IMPORT square IN "./graph/square.ob07";`
И так проще сделать, к тому же.

**Comment by prospero78** [comment]
Ещё проще:
```pascal
IMPORT square := "./graph/square.ob07";
```

**Comment by AntKrotov** [comment]
`
IMPORT mSqr := "./graph/square.ob07";
`

Выглядит довольно хорошо, мне понравилось.
И, похоже, особых трудностей в реализации не будет.

**Comment by prospero78** [comment]
А вообще, согласен. Не надо правила переутяжелять, соображения два:
 - явное лучше неявного (т.е. ЭТО глазами будет видно);
- чем проще компилятор, тем лучше.

**Comment by AntKrotov** [comment]
Я исправил работу с относительными путями (вроде бы). Проверяй.

**Comment by prospero78** [comment]
Ага. Посмотрим))

**Comment by AntKrotov** [comment]
Не может быть то же самое
типа такого:

Compiler
index out of range
module: HOST
line: 83

Что пишет вообще?

**Comment by prospero78** [comment]
Может я старый вариант использовал?.... Хм. Пока нет времени на проверку. Чтобы точно диагностировать, просьба Антон -- включай в вывод метку сборки и дату у компилятора.

**Comment by AntKrotov** [comment]
Понял, буду добавлять дату в вывод. Хорошо, когда будет время, тогда и проверишь. Торопиться некуда.

**Comment by prospero78** [comment]
```bash
walera@walera-lin:~/coding/gowork/src/github.com/prospero78/obGraph$ make run.app
Compiler "../src/Main.ob07" linux64exe -out "../bin/main"

Akron Oberon Compiler v1.43 (64-bit)
Copyright (c) 2018-2020, Anton Krotov
--------------------------------------------

file /home/walera/coding/gowork/src/github.com/prospero78/obGraph/lib/Linux64/RTL.ob07 not found
make: *** [Makefile:2: run.app] Ошибка 1
```
Хм... Похоже, ищет библиотеки в каталоге проекта.

**Comment by AntKrotov** [comment]
Ладно, вечером посмотрю.

**Comment by AntKrotov** [comment]
Работает. Я изменил Makefile из твоего репозитория на такой (указал относительный путь к новому компилятору):

run.app:
	**../oberon/Compiler** "./src/Main.ob07" linux64exe -out "./bin/main"
	./bin/main

Компилируется и запускается, только терминал пишет:

./Makefile1: строка 1: run.app:: команда не найдена

Но это не влияет на работу компилятора.

**Comment by prospero78** [comment]
С явным указанием относительных путей работает. (* И с самог оначала так работало *)
Я хотел запихнуть компиль с либами в `/home/walera/bin` и вызывать компилер без всяких путей:
`Compiler "./src/Main.ob07" linux64exe -out "./bin/main"`
И вот в таком варианте -- уже нет.

**Comment by AntKrotov** [comment]
Раньше не так работало. Раньше, относительный путь к проекту задавался только относительно компилятора. Теперь -- относительно рабочего (текущего) каталога. Компилятор должен знать свое расположение, чтобы найти папку /lib/. Получает он эту информацию из нулевого параметра командной строки. Как еще передать ему собственное расположение -- я не знаю. Пока же, чтобы не таскать компилятор в каждый проект, можно попробовать положить в проект два системных модуля API и RTL для соответствующей ОС. Компилятор сначала ищет модули в папке проекта и только потом в /lib/. Правда, если потребуется скомпилировать проект для другой ОС, то придется заменить API и RTL в проекте. Или сделать универсальные API/RTL с применением условной компиляции.

**Comment by prospero78** [comment]
Эмм... Есть же команда `pwd`, которая показывает текущий каталог. Вот результат `pwd` и подставлять перед обращением к `lib`.

**Comment by AntKrotov** [comment]
Так и сделано, только текущий каталог # каталог компилятора.

**Comment by prospero78** [comment]
Может, добавить экспорт переменной окружения для библиотек? И если её нет, выдавать предупреждение?

**Comment by AntKrotov** [comment]
Над этим надо подумать. Еще не приходилось работать с переменными окружения.

**Comment by prospero78** [comment]
Когда занимаешься локальной отладкой -- очень удобно программу после запуска конфигурировать. На сервере нет переменной окружения -- значит куча кода автоматом игнорируется.

**Comment by AntKrotov** [comment]
Я сделал импорт с указанием пути. Только через "IN". Так оказалось проще.
`IMPORT mod IN "./lib/module.ob07"`
Слэш можно использовать любой: "/" или "\\" -- без разницы. Тестировал на Windows, но на Linux тоже должно работать.

**Comment by prospero78** [comment]
Да, относительный импорт работает.

**Comment by prospero78** [comment]
Хм. Что-то сломалось.
```bash
compiling (14) Main (SYSTEM)

  error  (66) (101:28) incompatible parameter
  file:  /home/walera/coding/gowork/src/github.com/prospero78/obGraph/src/Main.ob07
make: *** [Makefile:3: run.app] Ошибка 1
```
Вроде, ничего не изменилось. Но что-то сломалось. Код (в сущности) не менял.

**Comment by AntKrotov** [comment]
Чтобы работало, надо просто поставить расширение файлов модулей.

вместо
`mSqr IN "./graph/square",
mEvn IN "./graph/event";`

так:
`mSqr IN "./graph/square.ob07",
mEvn IN "./graph/event.ob07";`

Но поведение странное, надо разбираться.

**Comment by prospero78** [comment]
Исправил везде расширения, собралось правильно. Чтобы поведение был правильное -- при импорте надо проверять принудительно расширение файлов.

**Comment by AntKrotov** [comment]
Исправлено. Теперь, если расширение не указано, будет ошибка: "файл не найден".
