### ISSUE TITLE
Алиасы типов

### ISSUE THREAD

**Issue by prospero78** [AntKrotov/oberon-07-compiler#8]
При попытке создать алиас INTEGER и использовать его в присвоении -- присвоение происходит без приведения алиаса к INTEGER.

**Comment by AntKrotov** [comment]
Без примера кода не очень понятно.
Алиас -- это точно тот же тип, только с другим названием. И это тоже следует из описания. Приведение не нужно.

**Comment by AntKrotov** [comment]
Oberon-07/16:

8.2.2. Arithmetic operators
...
The operators +, −, *, and / apply to operands of numeric types. Both operands must be of the
**same type**, which is also the type of the **result**. When used as unary operators, − denotes sign
inversion and + denotes the identity operation.

9.1. Assignments
...
The type of the expression must be the **same** as that of the designator.
...

Однако, что такое "Same types" в репорте не написано.

Определение есть в репорте Oberon-2:

Same types
Two variables a and b with types Ta and Tb are of the same type if

Ta and Tb are both denoted by the same type identifier, or
**Ta is declared to equal Tb in a type declaration of the form Ta = Tb**, or
a and b appear in the same identifier list in a variable, record field, or formal parameter declaration and are not open arrays.

Oberon-2 -- это, конечно, другой язык, но Вирт является соавтором этого языка.
Точно так же ведет себя и КП, и другие известные мне реализации Оберона-07.
Я считаю, что алиасы введены только для сокращения записи, как в Обероне-2/КП.
Нет оснований считать, что Оберон-07 надежнее других диалектов Оберона.

**Comment by prospero78** [comment]
Оберон-07 надёжней. Хотя бы потому, что он меньше, и типов в нём меньше, и вообще он меньше))
https://docs.google.com/document/d/1qcldcIVZ0SfBPa7IS3D_Ty35mki1YeCcB2N2CXrv9Fo/edit?usp=sharing -- специально смотрел в репорт Оберон-07 -- там нет определения, что ты привёл, так что, по дефолту можно предположить, что приведённое тобой описание верно, но предполагаю, что нет.

**Comment by prospero78** [comment]
Репорт не описывает как нужно делать Оберон для конкретной машины. Это некий общий профиль, мета-модель. А детали реализации остаются на совести реализатора конкретного варианта Оберона.
